name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.11"
      - name: Build Windows exe
        run: |
          pip install PyQt6 pyinstaller
          pyinstaller --onefile --windowed --name "yt-dlp GUI" ytdlp_gui.py
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: yt-dlp-GUI-Windows
          path: "dist/yt-dlp GUI.exe"

  macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.11"
      - name: Build macOS app
        run: |
          pip install PyQt6 py2app
          python setup.py py2app
          cd dist && zip -r "yt-dlp-GUI-macOS.zip" "yt-dlp GUI.app"
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: yt-dlp-GUI-macOS
          path: dist/yt-dlp-GUI-macOS.zip
